environment:
  VSVER: 14
  AWS_ACCESS_KEY_ID:
    secure: bSmjFOhp+jOCcRNdq/i136ZjTrIMLGURIsyEfMQEXH4=
  AWS_SECRET_ACCESS_KEY:
    secure: ezJ5cYLOCYDZcsXhfS4hgVC0+T67i2HE0++OVWE8ZEns6aR+KqnqB331x1oPfipO

platform:
  - x86
  # - x64

before_build:
  - ps: >-
      If ($env:Platform -Match "x86") {
        $env:PCRE_PLATFORM="Win32"
        $env:JAVA_HOME="c:/Program Files (x86)/Java/jdk1.8.0"
        $env:VCVARS_PLATFORM="x86"
        $env:LANG_PLATFORM=""
      } Else {
        $env:PCRE_PLATFORM="x64"
        $env:JAVA_HOME="c:/Program Files/Java/jdk1.8.0"
        $env:VCVARS_PLATFORM="amd64"
        $env:LANG_PLATFORM="-x64"
      }
  - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
  - echo "Using Visual Studio %VSVER%.0 at %VSCOMNTOOLS%"
  - call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" %VCVARS_PLATFORM%
  - git submodule update --init
  - choco install make

build_script:
  - gradlew.bat --info build

artifacts:
  - path: build/libs/*.jar
    name: jar

deploy_script:
  - if "%APPVEYOR_REPO_TAG%"=="true" (gradlew.bat publish -xcompileJavacpp)

cache:
  - C:\Users\appveyor\.gradle

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
