environment:
  global:
    PGHOST: 127.0.0.1
    PGPORT: 5432
    PGUSER: postgres
    PGPASSWORD: Password12!
    PGDATABASE: appveyordb
  matrix:
    - VSVER: 14

platform:
  - x86
  - x64

services:
  - postgresql94

before_build:
  - ps: >-
      If ($env:Platform -Match "x86") {
        $env:PCRE_PLATFORM="Win32"
        $env:JAVA_HOME="c:/Program Files (x86)/Java/jdk1.8.0"
        $env:VCVARS_PLATFORM="x86"
        $env:LANG_PLATFORM=""
      } Else {
        $env:PCRE_PLATFORM="x64"
        $env:JAVA_HOME="c:/Program Files/Java/jdk1.8.0"
        $env:VCVARS_PLATFORM="amd64"
        $env:LANG_PLATFORM="-x64"
      }
  - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
  - echo "Using Visual Studio %VSVER%.0 at %VSCOMNTOOLS%"
  - call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" %VCVARS_PLATFORM%
  - call "C:\Program Files\PostgreSQL\9.4\bin\createdb" %PGDATABASE%
  - git submodule update --init

build_script:
  - gradlew.bat --info build

artifacts:
  - path: build/libs/*.jar
    name: libs

  - path: build/reports
    name: reports
