environment:
  matrix:
    - VSVER: 14

platform:
  - x86
  #- x64

before_build:
  - ps: >-
      If ($env:Platform -Match "x86") {
        $env:PCRE_PLATFORM="Win32"
        $env:JAVA_HOME="c:/Program Files (x86)/Java/jdk1.8.0"
        $env:VCVARS_PLATFORM="x86"
        $env:LANG_PLATFORM=""
      } Else {
        $env:PCRE_PLATFORM="x64"
        $env:JAVA_HOME="c:/Program Files/Java/jdk1.8.0"
        $env:VCVARS_PLATFORM="amd64"
        $env:LANG_PLATFORM="-x64"
      }
  - ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
  - echo "Using Visual Studio %VSVER%.0 at %VSCOMNTOOLS%"
  - call "%VSCOMNTOOLS%\..\..\VC\vcvarsall.bat" %VCVARS_PLATFORM%
  - git submodule update --init

build_script:
  - gradlew.bat --info build shadowJar

artifacts:
  - path: build/libs/*.jar
    name: jar

deploy:
  provider: GitHub
  auth_token:
    secure: 6ZDfiJcBv9dQpihK+9mfiFXJpwhsjEAZbnudxX/BnvQEvosjV0X4E8+Oinys64Ap
  artifact: jar
  on:
    branch: master
    appveyor_repo_tag: true
